### ISSUE TITLE
加油

### ISSUE THREAD

**Issue by cmzz** [kulokai/weapp_wechat_miniapp_sdk#1]
这是目前能找到的实现的最完整的sdk了

**Comment by kulokai** [comment]
谢谢你的鼓励，剩余的功能我也会努力完善的

**Comment by tnevel** [comment]
您好，这个可以获取用户的openid  用户信息等信息吗。

**Comment by kulokai** [comment]
本小程序SDK是封装了小程序服务端接口的SDK。
        它不具备前端接口的功能。
        您需要获取用户信息和openid，要通过小程序端来获取
        详情参考：https://mp.weixin.qq.com/debug/wxadoc/dev/api/open.html#wxgetuserinfoobject 
        您在小程序端获取用户信息之后，可以上传至服务端储存

@tnevel

**Comment by kulokai** [comment]
@tnevel

**Comment by tnevel** [comment]
composer require jiaweixs/weapp  的版本没有github 的高呢！差别很多。少了不少功能 ！

**Comment by kulokai** [comment]
composer上已更新1.2版本
@tnevel
